# Generated by Django 3.0.3 on 2020-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absentelkom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_absen_ami',
            name='id_absen_ami',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
